spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks_service
    username: postgres # todo hide later
    password: postgres # todo hide later
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migrations
    baseline-on-migrate: true

jwt:
  token:
    signing-key: e35428d40366009872c5d9ec7a794b5445425a46cd5a5bfd35957093716a42f3

server:
  port: 8081