spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks_service
    username: postgres # todo hide later
    password: postgres # todo hide later
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migrations
    baseline-on-migrate: true

server:
  port: 8081