CREATE TABLE users (
    user_id BIGSERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(150) NOT NULL,
    email VARCHAR(100) UNIQUE,
    role VARCHAR(100) NOT NULL,
    register_at TIMESTAMP DEFAULT NOW()
);